name: RedEarthResources
favicon: null
layout_spectrum: 0.23667228478007019
typography_spectrum: 0.25530548323877156
title: Red Earth Resources
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.03035188582725823
  lightness: 0.2758946588728577
  saturation: 0.3801504571456462
  rhythmicContrast: 0.03998670191504061
purpose: []
